### ISSUE TITLE
panic (sigsegv) in dnssd.probeAtInterface()

### ISSUE THREAD

**Issue by chinenual** [brutella/dnssd#22]
github.com/brutella/dnssd v1.1.1
MacOS 10.14.6 (Mojave)
go version go1.14.1 darwin/amd64
 

I've been successfully using the library for some time, but in the last few days, my program has been crashing at unpredictable times with the following panic stack trace.

Here's how I start the responder:

```go
	cfg := dnssd.Config{
		Name: serviceName,
		Type: "_osc._udp",
		Port: int(oscListenPort),
	}
	var service dnssd.Service
	if service, err = dnssd.NewService(cfg); err != nil {
		return
	}
	var responder dnssd.Responder
	if responder, err = dnssd.NewResponder(); err != nil {
		return
	}
	if _, err = responder.Add(service); err != nil {
		return
	}

	go func() {
		ctx, cancel := context.WithCancel(context.Background())
		responderCancel = cancel
		defer cancel()

		if err = responder.Respond(ctx); err != nil {
			return
		}
	}()
```

How can I help get more useful debugging info so you can help diagnose?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13a6946]

goroutine 3864 [running]:
github.com/brutella/dnssd.probeAtInterface(0x164fd40, 0xc001bb5880, 0x1650e40, 0xc0009cd440, 0xc00ad31670, 0xe, 0x158de5c, 0x9, 0x158c55e, 0x5, ...)
	/Users/tynor/go/pkg/mod/github.com/brutella/dnssd@v1.1.1/probe.go:178 +0x8f6
github.com/brutella/dnssd.probe(0x164fd40, 0xc001bb5880, 0x1650e40, 0xc0009cd440, 0xc00ad31670, 0xe, 0x158de5c, 0x9, 0x158c55e, 0x5, ...)
	/Users/tynor/go/pkg/mod/github.com/brutella/dnssd@v1.1.1/probe.go:114 +0x337
github.com/brutella/dnssd.probeService(0x164fd40, 0xc001bb5880, 0x1650e40, 0xc0009cd440, 0xc00ad31670, 0xe, 0x158de5c, 0x9, 0x158c55e, 0x5, ...)
	/Users/tynor/go/pkg/mod/github.com/brutella/dnssd@v1.1.1/probe.go:61 +0x35b
github.com/brutella/dnssd.ReprobeService(0x164fd40, 0xc001bb5880, 0xc00ad31670, 0xe, 0x158de5c, 0x9, 0x158c55e, 0x5, 0xc001cf7c40, 0x37, ...)
	/Users/tynor/go/pkg/mod/github.com/brutella/dnssd@v1.1.1/probe.go:49 +0x14c
github.com/brutella/dnssd.(*responder).reprobe(0xc00b050e80, 0xc000010b28)
	/Users/tynor/go/pkg/mod/github.com/brutella/dnssd@v1.1.1/responder.go:348 +0x13b
created by github.com/brutella/dnssd.(*responder).respond
	/Users/tynor/go/pkg/mod/github.com/brutella/dnssd@v1.1.1/responder.go:248 +0x474
```

**Comment by chinenual** [comment]
OK - I added some extra debugging printfs near the log.Debug that triggered the error and find that the `req.iface` field is nil (hence the attempt to print `req.iface.Name` in the following pukes:

```go
	log.Debug.Printf("%v:%d@%s denies A\n", req.from.IP, req.from.Port, req.iface.Name)
```

So... I can add some guards around the printf to not try to dereference `req.iface` if it is nil, but before I just hack that fix into my copy, can anyone suggest why `req.iface` might be nil and does that suggest a deeper problem that I should be worried about?

**Comment by brutella** [comment]
Should be fixed now.
