### ISSUE TITLE
Panic when request interfaces are nil

### ISSUE THREAD

**Issue by rblenkinsopp** [brutella/dnssd#34]
Attempting to create a simple service following the sample in [HAP](https://github.com/brutella/hap),

### Steps to Reproduce

1. Run the HAP sample application shown in the README.md.
2. Notice that it panics in DNSSD with the following stack-trace:
```
goroutine 7 [running]:
github.com/brutella/dnssd.(*Service).IPsAtInterface(0xc0000916b8, 0x0)
        C:/Users/rober/go/pkg/mod/github.com/brutella/dnssd@v1.2.2/service.go:154 +0x3d
github.com/brutella/dnssd.A({{0xc0000299b0, 0xa}, {0x99a57d, 0x9}, {0x998f38, 0x5}, {0xc0000299c0, 0xc}, 0xc0001c2f00, 0x0, ...}, ...)
[signal C:/Users/rober/go/pkg/mod/github.com/brutella/dnssd@v1.2.2/dns.go:116 +0x39
github.com/brutella/dnssd.containsConflictingAnswers(0xc0002581f8, 0xc000006820)
        C:/Users/rober/go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:465 +0xbb
github.com/brutella/dnssd.findConflicts(0xc0002581f8, {0xc000208050, 0x1, 0x1?})
        C:/Users/rober/go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:446 +0x9b
github.com/brutella/dnssd.(*responder).handleRequest(0xc0001c4700, 0xc0002581f8)
        C:/Users/rober/go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:238 +0x195
github.com/brutella/dnssd.(*responder).respond(0xc0001c4700, {0xa3df30, 0xc0001d8300})
        C:/Users/rober/go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:203 +0x1d4
github.com/brutella/dnssd.(*responder).Respond(0xc0001c4700, {0xa3df30, 0xc0001d8300})
        C:/Users/rober/go/pkg/mod/github.com/brutella/dnssd@v1.2.2/responder.go:113 +0x3ef
github.com/brutella/hap.(*Server).listenAndServe.func1()
        C:/Users/rober/go/pkg/mod/github.com/brutella/hap@v0.0.14/server.go:205 +0x37
created by github.com/brutella/hap.(*Server).listenAndServe
        C:/Users/rober/go/pkg/mod/github.com/brutella/hap@v0.0.14/server.go:204 +0x465

Process finished with the exit code 2
```

### Expected Behaviour

The HAP server announces correctly on DNSSD and no panic occurs.

### Investigation

Looking into this further, it's failing because the `iface` parameter being passed to the `A()` and `AAAA()` is `nil` which causes those functions to fail.

It's `nil` because the implementation of `payloadHandler.ReadFrom` which is used internally by `mdnsConn.readInto`, doesn't set the `cm` parameter (leaving it `nil`), which the rest of the `dnssd` stack fails to deal with correctly.

### Possible Fixes

- Have the `A()` and `AAAA()` methods deal with a possibly `nil` interface (`iface`) argument.
- Prevent the `iface` parameter of the `dnssd.request` struct from being `nil` in the first place.

I've tested the first of these two options and DNSSD then exhibits the correct behaviour (and I will submit an MR for this) however the second possible fix might be the better solution (though both can be implemented together to be suitable defensive).

### Reproduction Machine Network Configuration

For additional reference, my network configuration which exposes this issue is (Public IPs and MACs redacted):
<details>
  <summary>`ipconfig /all` output</summary>
  
```
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : xxxx.local
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection I217-V
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx(Preferred)
   Temporary IPv6 Address. . . . . . : xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx(Deprecated)
   Temporary IPv6 Address. . . . . . : xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx(Preferred)
   Link-local IPv6 Address . . . . . : xxxx::xxxx:xxxx:xxxx:xxxx%X(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.4.1.2(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Lease Obtained. . . . . . . . . . : 14 May 2022 08:20:32
   Lease Expires . . . . . . . . . . : 16 May 2022 11:01:35
   Default Gateway . . . . . . . . . : xxxx::xxxx:xxxx:xxxx:xxxx%X
                                       10.4.0.1
   DHCP Server . . . . . . . . . . . : 10.4.0.1
   DHCPv6 IAID . . . . . . . . . . . : 213671924
   DHCPv6 Client DUID. . . . . . . . : XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX
   DNS Servers . . . . . . . . . . . : 10.4.0.1
   Primary WINS Server . . . . . . . : 10.4.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Unknown adapter Private Internet Access:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Private Internet Access Network Adapter
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter WiFi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : xxxx.local
   Description . . . . . . . . . . . : Broadcom 802.11ac Network Adapter
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : xxxx::xxxx:xxxx:xxxx:xxxx%X(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.29.112.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 721425757
   DHCPv6 Client DUID. . . . . . . . : XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX
   NetBIOS over Tcpip. . . . . . . . : Enabled
```
</details>

**Comment by rblenkinsopp** [comment]
I've submitted an MR which takes the first proposed approach above. This appears to resolve the issue in my testing but I'd be interested to understand the route of this issue further.

**Comment by brutella** [comment]
`cm` is the control message and should include the network interface – see [mdns.go](https://github.com/brutella/dnssd/blob/master/mdns.go#L146).

We should investigate why this is nil.

**Comment by rblenkinsopp** [comment]
So my debugger is showing the call `ipv4.ReadFrom` in [mdns.go](https://github.com/brutella/dnssd/blob/master/mdns.go#L220) is calling through to `payload_nocmsg.go` in `golang.net/x.net` (note the this is the No CMsg variant).

From looking at the `go:build` statements, it looks like this is because the NoCMsg variant is always used on non-Unix platforms IE Windows like this issue is exhibiting on.

**Comment by AlexxIT** [comment]
I can confirm, solution fix work on Windows

**Comment by rblenkinsopp** [comment]
Thanks, @AlexxIT, @brutella would you consider merging the MR to work around the issue? It seems like it's sensible defensive programming, even though I agree it would be nice to have the underlying issue resolved.

**Comment by zuozhehao** [comment]
https://github.com/brutella/dnssd/blob/master/mdns.go#L146

I have the same problem on Windows 10 Pro.

It will get an error message in my system `not implemented on windows/amd64` @rblenkinsopp @brutella
